apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payflow
  labels:
    app.kubernetes.io/part-of: payflow
    app.kubernetes.io/component: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
