apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: payflow
  labels:
    app.kubernetes.io/part-of: payflow
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
