apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: payflow
  labels:
    app.kubernetes.io/part-of: payflow
    app.kubernetes.io/component: webhook-service
spec:
  type: ClusterIP
  selector:
    app: webhook-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
