apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: payflow
  labels:
    app.kubernetes.io/part-of: payflow
    app.kubernetes.io/component: notification-service
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  PAYFLOW_WEBHOOK_DISPATCH_BASE_URL: http://webhook-service:8083
